spring:
  application:
    name: order

  # JPA가 테이블을 생성한 후에 data.sql 실행
  jpa:
    defer-datasource-initialization: true

# Resilience4j 설정
# 외부 결제 API 호출 시 타임아웃 설정을 통해 무한 대기를 방지
resilience4j:
  timelimiter:
    instances:
      payment:
        timeout-duration: 5s              # 외부 결제 API 호출 시 5초 타임아웃
        cancel-running-future: true        # 타임아웃 발생 시 진행 중인 작업 취소

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC